version: '3.8'
services:
  akatsuki-db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3307:3306
    environment:
    #   MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: akatsuki-db
    #   MYSQL_USER: admin
    #   MYSQL_PASSWORD: admin